import { Button, Card, Form, Input, Modal, Radio, Select, Space, Switch, Tabs, Typography, message } from "antd";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { useAlbums } from "../features/albums/api";
import {
  type GuideBlock, type GuideModule, type TOCItem, useAutoTOC, useCreateBlock, useCreateModule,
  useDeleteBlock, useDeleteModule, useGuide, useReplaceGuideAlbums, useReplaceTOC,
  useSortBlocks, useSortModules, useUpdateBlock, useUpdateModule
} from "../features/guides/api";

const templates=["itinerary","expense","checklist","transport","photo","tips"];
const blockTypes=["markdown","image","video","link","tasks","warning","divider"];

export function AdminGuideEditorPage(){
  const{id=""}=useParams(),q=useGuide(id,true),albums=useAlbums(true);
  const createModule=useCreateModule(),updateModule=useUpdateModule(),deleteModule=useDeleteModule();
  const createBlock=useCreateBlock(),updateBlock=useUpdateBlock(),deleteBlock=useDeleteBlock();
  const sortModules=useSortModules(),sortBlocks=useSortBlocks(),replaceTOC=useReplaceTOC(),autoTOC=useAutoTOC(),replaceAlbums=useReplaceGuideAlbums();
  const[selected,setSelected]=useState<string>(),[moduleModal,setModuleModal]=useState(false),[blockModal,setBlockModal]=useState(false),[editingBlock,setEditingBlock]=useState<GuideBlock>();
  const[moduleForm]=Form.useForm(),[blockForm]=Form.useForm();const[msg,holder]=message.useMessage();
  const module=q.data?.modules.find(x=>x.id===selected);
  useEffect(()=>{if(!selected&&q.data?.modules[0])setSelected(q.data.modules[0].id)},[q.data,selected]);
  const albumIDs=useMemo(()=>q.data?.albums?.map(x=>x.id)??[],[q.data]);
  async function saveModule(values:any){const input={...values,data_version:1,structured_data:values.kind==="structured"?JSON.parse(values.structured_json||"[]"):undefined};if(moduleModal&&moduleForm.getFieldValue("id"))await updateModule.mutateAsync({guideId:id,moduleId:moduleForm.getFieldValue("id"),input});else await createModule.mutateAsync({guideId:id,input});setModuleModal(false)}
  async function saveBlock(values:any){const input={type:values.type,data_version:1,data:JSON.parse(values.data_json||"{}")};if(editingBlock)await updateBlock.mutateAsync({guideId:id,moduleId:module!.id,blockId:editingBlock.id,input});else await createBlock.mutateAsync({guideId:id,moduleId:module!.id,input});setBlockModal(false);setEditingBlock(undefined)}
  function reorder<T extends {id:string}>(items:T[],index:number,delta:number){const next=[...items],target=index+delta;if(target<0||target>=next.length)return items;[next[index],next[target]]=[next[target],next[index]];return next}
  return <div className="admin-page-stack">{holder}<div className="panel-actions"><div><Typography.Title>{q.data?.guide.title??"Guide 编辑器"}</Typography.Title><Typography.Paragraph type="secondary">模块、内容、目录、相册与实时数据预览。</Typography.Paragraph></div><Button href="/admin/guides">返回列表</Button></div>
    <div className="guide-editor-shell"><aside>{q.data?.modules.map((m,i)=><Card size="small" key={m.id} onClick={()=>setSelected(m.id)} className={m.id===selected?"selected-card":""}><Space direction="vertical"><b>{m.name}</b><Space><Button size="small" onClick={e=>{e.stopPropagation();moduleForm.setFieldsValue({...m,id:m.id,structured_json:JSON.stringify(m.structured_data??[],null,2)});setModuleModal(true)}}>编辑</Button><Button size="small" onClick={e=>{e.stopPropagation();void sortModules.mutateAsync({guideId:id,ids:reorder(q.data!.modules,i,-1).map(x=>x.id)})}}>↑</Button><Button size="small" onClick={e=>{e.stopPropagation();void sortModules.mutateAsync({guideId:id,ids:reorder(q.data!.modules,i,1).map(x=>x.id)})}}>↓</Button><Button size="small" danger onClick={e=>{e.stopPropagation();void deleteModule.mutateAsync({guideId:id,moduleId:m.id})}}>删</Button></Space></Space></Card>)}<Button block type="primary" onClick={()=>{moduleForm.resetFields();setModuleModal(true)}}>新增模块</Button></aside>
      <section>{module?<><Typography.Title level={3}>{module.name}</Typography.Title>{module.kind==="structured"?<StructuredEditor module={module} onSave={async data=>{await updateModule.mutateAsync({guideId:id,moduleId:module.id,input:{name:module.name,kind:module.kind,template:module.template,data_version:1,structured_data:data,hidden:module.hidden}});msg.success("结构化模块已保存")}}/>:<><Button onClick={()=>{blockForm.resetFields();setEditingBlock(undefined);setBlockModal(true)}}>新增内容块</Button>{module.blocks?.map((b,i)=><Card key={b.id} size="small" title={b.type} extra={<Space><Button size="small" onClick={()=>void sortBlocks.mutateAsync({guideId:id,moduleId:module.id,ids:reorder(module.blocks??[],i,-1).map(x=>x.id)})}>↑</Button><Button size="small" onClick={()=>void sortBlocks.mutateAsync({guideId:id,moduleId:module.id,ids:reorder(module.blocks??[],i,1).map(x=>x.id)})}>↓</Button><Button size="small" onClick={()=>{setEditingBlock(b);blockForm.setFieldsValue({type:b.type,data_json:JSON.stringify(b.data,null,2)});setBlockModal(true)}}>编辑</Button><Button size="small" danger onClick={()=>void deleteBlock.mutateAsync({guideId:id,moduleId:module.id,blockId:b.id})}>删除</Button></Space>}><pre>{JSON.stringify(b.data,null,2)}</pre></Card>)}</>}</>:<Typography.Text>请选择模块</Typography.Text>}</section>
      <aside><Tabs items={[{key:"toc",label:"目录",children:<TOCEditor value={q.data?.toc??[]} modules={q.data?.modules??[]} onSave={items=>replaceTOC.mutateAsync({guideId:id,items})} onAuto={()=>autoTOC.mutateAsync(id)}/>},{key:"albums",label:"相册",children:<><Select mode="multiple" style={{width:"100%"}} defaultValue={albumIDs} options={albums.data?.items.map(a=>({value:a.id,label:a.name}))} onChange={ids=>void replaceAlbums.mutateAsync({guideId:id,ids})}/></>}]} /></aside></div>
    <Modal open={moduleModal} onCancel={()=>setModuleModal(false)} onOk={()=>moduleForm.submit()}><Form form={moduleForm} layout="vertical" onFinish={saveModule}><Form.Item name="id" hidden><Input/></Form.Item><Form.Item name="name" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="kind" label="类型" initialValue="content"><Radio.Group options={[{value:"content",label:"普通内容"},{value:"structured",label:"结构化"}]}/></Form.Item><Form.Item name="template" label="模板"><Select allowClear options={templates.map(value=>({value,label:value}))}/></Form.Item><Form.Item name="structured_json" label="结构化数据 JSON" extra="按所选模板填写，保存时服务端严格校验。"><Input.TextArea rows={10}/></Form.Item><Form.Item name="hidden" label="隐藏" valuePropName="checked"><Switch/></Form.Item></Form></Modal>
    <Modal open={blockModal} onCancel={()=>setBlockModal(false)} onOk={()=>blockForm.submit()}><Form form={blockForm} layout="vertical" onFinish={saveBlock}><Form.Item name="type" label="类型" rules={[{required:true}]}><Select options={blockTypes.map(value=>({value,label:value}))}/></Form.Item><Form.Item name="data_json" label="内容 JSON" rules={[{required:true}]}><Input.TextArea rows={12}/></Form.Item></Form></Modal>
  </div>
}

function StructuredEditor({module,onSave}:{module:GuideModule;onSave:(data:unknown)=>Promise<void>}){const[value,setValue]=useState(JSON.stringify(module.structured_data??[],null,2));useEffect(()=>setValue(JSON.stringify(module.structured_data??[],null,2)),[module]);return <><Typography.Paragraph type="secondary">{module.template} 专用数据；字段限制由服务端校验并提示。</Typography.Paragraph><Input.TextArea rows={20} value={value} onChange={e=>setValue(e.target.value)}/><Button type="primary" onClick={()=>void onSave(JSON.parse(value))}>保存并预览</Button></>}
function TOCEditor({value,modules,onSave,onAuto}:{value:TOCItem[];modules:GuideModule[];onSave:(items:TOCItem[])=>Promise<unknown>;onAuto:()=>Promise<unknown>}){const[text,setText]=useState(JSON.stringify(value,null,2));useEffect(()=>setText(JSON.stringify(value,null,2)),[value]);return <><Typography.Paragraph type="secondary">目录目标必须属于当前 Guide，级别仅支持 1 或 2。</Typography.Paragraph><Input.TextArea rows={14} value={text} onChange={e=>setText(e.target.value)}/><Space><Button type="primary" onClick={()=>void onSave(JSON.parse(text).map((x:any,i:number)=>({...x,sort:i})))}>保存目录</Button><Button onClick={()=>void onAuto()}>按可见模块自动生成</Button></Space><Typography.Text type="secondary">{modules.length} 个模块可关联</Typography.Text></>}
